Name: Manthan Solanki

ID:   202318012

In [1]:
import sklearn
from sklearn.datasets import fetch_20newsgroups
import pandas as pd
import json
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np


1. You need to implement a TF-IDF vectorizer to convert a collection of documents 
into TF-IDF vectors. You can use the sklearn’s inbuild datase        
fetch_20newsgroups.

In [2]:
# for vectorizing documents
def get_vecs(data):
    
    vec = TfidfVectorizer(stop_words = 'english')
    mat = vec.fit_transform(data)
    return mat
    
data = fetch_20newsgroups(subset='train')
# data = data['data']

tfidf_vecs = get_vecs(data['data'])
print('TD-IDF vectors:  ')
print(tfidf_vecs)

TD-IDF vectors:  
  (0, 86416)	0.14330464297977982
  (0, 35135)	0.10188109676312235
  (0, 65968)	0.10658183340971177
  (0, 114195)	0.06002582888934523
  (0, 78809)	0.06524029473980168
  (0, 76578)	0.0752490171119318
  (0, 57203)	0.16977226500364592
  (0, 67023)	0.07965653370342658
  (0, 63238)	0.09086750717799585
  (0, 95944)	0.11792442679286105
  (0, 127721)	0.0660283455431985
  (0, 109044)	0.11811852219269026
  (0, 51651)	0.10581100308545811
  (0, 83103)	0.09633120317294654
  (0, 113755)	0.1926949257821117
  (0, 73061)	0.04662587301170703
  (0, 34131)	0.09493746671845804
  (0, 101175)	0.08899924936054199
  (0, 105907)	0.10749912859686628
  (0, 35560)	0.1446512460011004
  (0, 26070)	0.10385185139503332
  (0, 108033)	0.08197182211166716
  (0, 99619)	0.06171903092868097
  (0, 48552)	0.1263844988551673
  (0, 34943)	0.18203649549572573
  :	:
  (11313, 106061)	0.11739285034416508
  (11313, 67469)	0.07888902121089117
  (11313, 63763)	0.11511167728184264
  (11313, 37359)	0.16552340600580592


2. Create a function to calculate the cosine similarity between two TF-IDF vectors.

In [3]:
# to get cosine similarity

def get_csn_sim(v1, v2):
    v1 = v1.reshape(len(v1), -1)
    v2 = v2.reshape(len(v2), -1)
    csn_sim = cosine_similarity(v1, v2)
    return csn_sim
    

tfidf_vecs = get_vecs(data['data'])

ind1 = np.random.randint(0, tfidf_vecs.shape[0])
ind2 = np.random.randint(0, tfidf_vecs.shape[0])

print('\nDocument 1: ', data['data'][ind1][:20])
print('\nDocument 2: ', data['data'][ind2][:20])

# cosine similarity between two docs

csn_sim = cosine_similarity(tfidf_vecs[ind1], tfidf_vecs[ind2])
csn_sim = np.round(csn_sim[0][0], 6) 
print('\nCosine Similarity between docs: ', csn_sim)



Document 1:  From: chen@citr.uq.o

Document 2:  From: ljbartel@naomi

Cosine Similarity between docs:  0.002769


In [4]:

idx = np.array([x for x in range(tfidf_vecs.shape[0])])

# splitting documents into train and test to get similarity
train_idx = np.random.choice(idx, size = int(0.8 * (tfidf_vecs.shape[0])), replace = False)
test_idx = np.setdiff1d(idx, train_idx)

train = tfidf_vecs[train_idx]
test = tfidf_vecs[test_idx]

csn_sim = cosine_similarity(train, test)
csn_sim = np.round(csn_sim, 6) 
print('\nCosine Similarity between docs: \n\n', csn_sim)



Cosine Similarity between docs: 

 [[0.002264 0.014679 0.037178 ... 0.00314  0.004641 0.005051]
 [0.012259 0.004546 0.00854  ... 0.005402 0.004967 0.005188]
 [0.009683 0.003884 0.006585 ... 0.006869 0.003635 0.00605 ]
 ...
 [0.055665 0.034321 0.007467 ... 0.00597  0.004286 0.014023]
 [0.015562 0.017432 0.016889 ... 0.019029 0.006591 0.02091 ]
 [0.010691 0.01063  0.00663  ... 0.008187 0.006292 0.008323]]


3. Implement a document similarity search function that takes a document as input
and returns a list of documents ranked by their similarity to the input document.

In [40]:
# document similarity search function

def doc_sim(idx):

    data = fetch_20newsgroups(subset='train')
    docs = data['data']
    d = docs[idx]
    
    docs.pop(idx)
    vec = TfidfVectorizer(stop_words = 'english')
    train = vec.fit_transform(docs)
    test = vec.transform([d])

    csn_sim = cosine_similarity(train, test)
    print('sim: ', csn_sim)
    indices = np.arange(len(csn_sim)).astype('int')
    print("indices:  ", indices)
    
    # csn_sim = np.append(csn_sim, indices, axis=1)
    
    sim_idx = np.argsort(csn_sim, axis=0).flatten()
    print('\nsim_idx: ', sim_idx)
    top_5 = sim_idx.argsort()[:-6:-1]
    print('min indices: ',   top_5)

    
    
    res = [docs[i][:30] for i in top_5]
    
    return np.array (res)

In [41]:

idx = np.random.randint(0, len(data['data']))
idx = doc_sim(idx)

print("List of Similar Documents: \n\n", idx)

# for i in idx:
#     print(data['data'][i][:10])

sim:  [[0.01702913]
 [0.00676701]
 [0.01859057]
 ...
 [0.003967  ]
 [0.01170542]
 [0.0147781 ]]
indices:   [    0     1     2 ... 11310 11311 11312]

sim_idx:  [4772 8665 9080 ... 1042 6431  890]
min indices:  [8864 7804 2991 2583 2632]
List of Similar Documents: 

 ['From: stusoft@hardy.u.washingt' 'From: klee@synoptics.com (Ken '
 'From: "danny hawrysio" <danny.' 'From: maynard@ramsey.cs.lauren'
 'From: vbv@r2d2.eeap.cwru.edu (']
